language: en-US
database:
  url: 'jdbc:h2:./medieval_factions_db;AUTO_SERVER=true;MODE=MYSQL;DATABASE_TO_UPPER=false'
  dialect: 'H2'
  username: 'sa'
  password: ''
players:
  maxPower: 20
  hoursToReachMaxPower: 12
  hoursToReachMinPower: 72
factions:
  initialPowerLevel: 5
  mobsSpawnInFactionTerritory: false
  powerIncreaseAmount: 2
  laddersPlaceableInEnemyFactionTerritory: true
  minutesBeforeInitialPowerIncrease: 30
  minutesBetweenPowerIncreases: 60
  warsRequiredForPvp: true
  factionOwnerMultiplier: 2.0
  officerPerMemberCount: 5
  factionOfficerMultiplier: 1.5
  powerDecreases: true
  minutesBetweenPowerDecreases: 1440
  minutesBeforePowerDecrease: 20160
  powerDecreaseAmount: 1
  maxNameLength: 20
  maxNumberGates: 5
  maxGateArea: 64
  surroundedChunksProtected: true
  zeroPowerFactionsGetDisbanded: false
  vassalPowerContributionMultiplier: 0.75
  nonMembersCanInteractWithDoors: false
  playersChatWithPrefixes: true
  maxClaimRadius: 3
  defaults:
    flags:
      mustBeOfficerToManageLand: true
      mustBeOfficierToInviteOthers: true
      alliesCanInteractWithLand: false
      vassalageTreeCanInteractWithLand: false
      neutral: false
      dynmapTerritoryColor: '#ff0000'
      territoryAlertColor: '#ffffff'
      prefixColor: '#ffffff'
      allowFriendlyFire: false
      acceptBonusPower: true