name: MedievalFactions
authors:
- DanTheTechMan
- Pasarus
- Caibinus
- Callum
- Richardhyy
- Mitras2
- Kaonami
- GoodLucky777
- Elafir
- Deej
- VoChiDanh
- alyphen
version: @version@
main: com.dansplugins.factionsystem.MedievalFactions
api-version: 1.13
softdepend: [dynmap, PlaceholderAPI]
description: Allows players to organise themselves into feudal, diplomatic, lawful groups akin to nations.
commands:
  medievalfactions:
    description: |
      Medieval Factions base command
    aliases: [mf]
    usage: /<command>
  faction:
    description: |
      Faction management command
    aliases: [f]
    usage: /<command> [create]